name: Hello Workflow

run-name: Running Hello World Workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
    Print-Hello-Job:
      runs-on: ubuntu-latest
      steps:
        - run: echo Hello, "${{ github.actor }}"
        - run: echo "🍏 This job's status is ${{ job.status }}."